#!/usr/bin/env node
// Cloudflare build step (Workers Builds "Build command": node cloudflare/build.mjs).
// 1. Packs the small-JSON collections into cf-packs/ so the static upload stays
//    under the free plan's 20,000-file limit (served back by cloudflare/packs.mjs).
// 2. Writes _headers (Cloudflare's version of netlify.toml [[headers]]).
// Both outputs are build artifacts (git-ignored); Netlify never sees them.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "cf-packs");
const MAX_PACK = 4 * 1024 * 1024;
const COLLECTIONS = [
  ["sketches-meta", "sketches-meta"],
  ["generated-meta", "generated-meta"],
  ["sketches/json", "sketches-json"],
];

function natural(a, b) {
  const na = parseFloat(a), nb = parseFloat(b);
  if (!isNaN(na) && !isNaN(nb) && na !== nb) return na - nb;
  return a < b ? -1 : a > b ? 1 : 0;
}

fs.rmSync(OUT, { recursive: true, force: true });
let packedFiles = 0;
for (const [dir, coll] of COLLECTIONS) {
  const src = path.join(ROOT, dir);
  if (!fs.existsSync(src)) continue;
  const names = fs.readdirSync(src).filter((n) => fs.statSync(path.join(src, n)).isFile()).sort(natural);
  const outDir = path.join(OUT, coll);
  fs.mkdirSync(outDir, { recursive: true });
  const files = {};
  let pack = 0, offset = 0, bufs = [];
  const flush = () => {
    if (!bufs.length) return;
    fs.writeFileSync(path.join(outDir, pack + ".bin"), Buffer.concat(bufs));
    pack++; offset = 0; bufs = [];
  };
  for (const n of names) {
    const b = fs.readFileSync(path.join(src, n));
    if (offset && offset + b.length > MAX_PACK) flush();
    files[n] = [pack, offset, b.length];
    bufs.push(b); offset += b.length;
  }
  flush();
  fs.writeFileSync(path.join(outDir, "index.json"), JSON.stringify({ files }));
  packedFiles += names.length;
  console.log(`packed ${names.length} files from ${dir}/ into ${pack} pack(s)`);
}

fs.writeFileSync(
  path.join(ROOT, "_headers"),
  [
    "# Generated by cloudflare/build.mjs from netlify.toml [[headers]] — do not edit.",
    "/paintings/*",
    "  Cache-Control: public, max-age=31536000, immutable",
    "/data/*",
    "  Cache-Control: public, max-age=3600",
    "/*.html",
    "  Cache-Control: public, max-age=300",
    "/js/*",
    "  Cache-Control: no-cache, must-revalidate",
    "",
  ].join("\n")
);
console.log(`wrote _headers; ${packedFiles} files will be served from packs`);
